# Comprehensive Neovim configuration
# Uses theme from config.homeModules.theme when available
{
  config,
  lib,
  pkgs,
  ...
}: let
  cfg = config.homeModules.neovim;
  themeCfg = config.homeModules.theme;

  # Map theme names to Neovim colorschemes and variants
  themeMap = {
    "catppuccin-mocha" = {
      colorscheme = "catppuccin";
      variant = "mocha";
    };
    "catppuccin-latte" = {
      colorscheme = "catppuccin";
      variant = "latte";
    };
    "tokyo-night" = {
      colorscheme = "tokyonight";
      variant = "night";
    };
    "everforest" = {
      colorscheme = "everforest";
      variant = "medium";
    };
  };

  # Determine colorscheme based on theme module or default
  selectedTheme = themeMap.${themeCfg.name} or themeMap."catppuccin-mocha";
  colorscheme = selectedTheme.colorscheme;

  # Get theme variant for plugins that need it
  themeVariant = selectedTheme.variant;

  # Lua configuration - comprehensive setup
  luaConfig = ''
    -- ============================================================================
    -- NEOVIM CONFIGURATION
    -- Generated by NixOS home-manager module
    -- ============================================================================

    -- ----------------------------------------------------------------------------
    -- LEADER KEY (must be set before plugins)
    -- ----------------------------------------------------------------------------
    vim.g.mapleader = " "
    vim.g.maplocalleader = " "

    -- ----------------------------------------------------------------------------
    -- SENSIBLE DEFAULTS
    -- ----------------------------------------------------------------------------

    local opt = vim.opt

    -- Line numbers
    opt.number = true           -- Show line numbers
    opt.relativenumber = true   -- Relative line numbers

    -- Indentation (2 spaces default, language-specific overrides below)
    opt.tabstop = 2             -- Tab width
    opt.shiftwidth = 2          -- Indent width
    opt.softtabstop = 2         -- Soft tab width
    opt.expandtab = true        -- Use spaces instead of tabs
    opt.smartindent = true      -- Smart auto-indenting

    -- Search
    opt.ignorecase = true       -- Case-insensitive search
    opt.smartcase = true        -- Case-sensitive if uppercase present
    opt.hlsearch = true         -- Highlight search results
    opt.incsearch = true        -- Incremental search

    -- UI
    opt.termguicolors = true    -- True color support
    opt.signcolumn = "yes"      -- Always show sign column
    opt.cursorline = true       -- Highlight current line
    opt.scrolloff = 8           -- Keep 8 lines above/below cursor
    opt.sidescrolloff = 8       -- Keep 8 columns left/right of cursor
    opt.wrap = false            -- Don't wrap lines
    opt.showmode = false        -- Mode shown in statusline
    opt.splitbelow = true       -- Horizontal splits below
    opt.splitright = true       -- Vertical splits right

    -- Clipboard (system clipboard integration)
    opt.clipboard = "unnamedplus"

    -- Mouse support
    opt.mouse = "a"

    -- Persistent undo
    opt.undofile = true
    opt.undolevels = 10000

    -- Performance
    opt.updatetime = 250        -- Faster completion
    opt.timeoutlen = 300        -- Faster key sequence completion

    -- Backup/swap (let Nix handle this)
    opt.swapfile = false
    opt.backup = false

    -- Better completion
    opt.completeopt = "menu,menuone,noselect"

    -- ----------------------------------------------------------------------------
    -- LANGUAGE-SPECIFIC INDENTATION
    -- 4 spaces for: Python, Rust, Go
    -- 2 spaces for: everything else
    -- ----------------------------------------------------------------------------

    vim.api.nvim_create_autocmd("FileType", {
      pattern = { "python", "rust", "go" },
      callback = function()
        vim.opt_local.tabstop = 4
        vim.opt_local.shiftwidth = 4
        vim.opt_local.softtabstop = 4
      end,
    })

    -- Go uses tabs
    vim.api.nvim_create_autocmd("FileType", {
      pattern = { "go" },
      callback = function()
        vim.opt_local.expandtab = false
      end,
    })

    -- ----------------------------------------------------------------------------
    -- COLORSCHEME
    -- Synced with system theme: ${colorscheme} (${themeVariant})
    -- ----------------------------------------------------------------------------

    -- Configure theme before loading
    ${
      if colorscheme == "catppuccin"
      then ''
        require("catppuccin").setup({
          flavour = "${themeVariant}",
          transparent_background = false,
          integrations = {
            telescope = true,
            gitsigns = true,
            treesitter = true,
            which_key = true,
            native_lsp = {
              enabled = true,
            },
          },
        })
      ''
      else if colorscheme == "tokyonight"
      then ''
        require("tokyonight").setup({
          style = "${themeVariant}",
          transparent = false,
        })
      ''
      else if colorscheme == "everforest"
      then ''
        vim.g.everforest_background = "medium"
        vim.g.everforest_enable_italic = 1
      ''
      else ""
    }

    vim.cmd.colorscheme("${colorscheme}")

    -- ----------------------------------------------------------------------------
    -- PLUGIN CONFIGURATIONS
    -- ----------------------------------------------------------------------------

    -- Treesitter: Syntax highlighting and code understanding
    require("nvim-treesitter.configs").setup({
      highlight = { enable = true },
      indent = { enable = true },
      incremental_selection = {
        enable = true,
        keymaps = {
          init_selection = "<C-space>",
          node_incremental = "<C-space>",
          scope_incremental = false,
          node_decremental = "<bs>",
        },
      },
    })

    -- Telescope: Fuzzy finder
    local telescope = require("telescope")
    local actions = require("telescope.actions")

    telescope.setup({
      defaults = {
        mappings = {
          i = {
            ["<C-j>"] = actions.move_selection_next,
            ["<C-k>"] = actions.move_selection_previous,
            ["<Esc>"] = actions.close,
          },
        },
        file_ignore_patterns = {
          "node_modules",
          ".git/",
          "target/",
          "dist/",
          "build/",
        },
      },
      pickers = {
        find_files = {
          hidden = true,
        },
      },
    })

    -- Oil.nvim: File explorer (vim-like)
    require("oil").setup({
      default_file_explorer = true,
      columns = { "icon" },
      view_options = {
        show_hidden = true,
      },
      keymaps = {
        ["g?"] = "actions.show_help",
        ["<CR>"] = "actions.select",
        ["<C-v>"] = "actions.select_vsplit",
        ["<C-s>"] = "actions.select_split",
        ["<C-t>"] = "actions.select_tab",
        ["<C-p>"] = "actions.preview",
        ["<C-c>"] = "actions.close",
        ["<C-l>"] = "actions.refresh",
        ["-"] = "actions.parent",
        ["_"] = "actions.open_cwd",
        ["`"] = "actions.cd",
        ["~"] = "actions.tcd",
        ["gs"] = "actions.change_sort",
        ["gx"] = "actions.open_external",
        ["g."] = "actions.toggle_hidden",
      },
    })

    -- Gitsigns: Git integration in the gutter
    require("gitsigns").setup({
      signs = {
        add = { text = "│" },
        change = { text = "│" },
        delete = { text = "_" },
        topdelete = { text = "‾" },
        changedelete = { text = "~" },
      },
      on_attach = function(bufnr)
        local gs = package.loaded.gitsigns

        local function map(mode, l, r, opts)
          opts = opts or {}
          opts.buffer = bufnr
          vim.keymap.set(mode, l, r, opts)
        end

        -- Navigation
        map("n", "]c", function()
          if vim.wo.diff then return "]c" end
          vim.schedule(function() gs.next_hunk() end)
          return "<Ignore>"
        end, { expr = true, desc = "Next hunk" })

        map("n", "[c", function()
          if vim.wo.diff then return "[c" end
          vim.schedule(function() gs.prev_hunk() end)
          return "<Ignore>"
        end, { expr = true, desc = "Previous hunk" })

        -- Actions
        map("n", "<leader>hs", gs.stage_hunk, { desc = "Stage hunk" })
        map("n", "<leader>hr", gs.reset_hunk, { desc = "Reset hunk" })
        map("n", "<leader>hp", gs.preview_hunk, { desc = "Preview hunk" })
        map("n", "<leader>hb", function() gs.blame_line({ full = true }) end, { desc = "Blame line" })
      end,
    })

    -- Toggleterm: Terminal integration
    require("toggleterm").setup({
      size = function(term)
        if term.direction == "horizontal" then
          return 15
        elseif term.direction == "vertical" then
          return vim.o.columns * 0.4
        end
      end,
      open_mapping = [[<C-\>]],
      hide_numbers = true,
      shade_terminals = true,
      start_in_insert = true,
      insert_mappings = true,
      terminal_mappings = true,
      persist_size = true,
      direction = "horizontal",
      close_on_exit = true,
      shell = vim.o.shell,
      float_opts = {
        border = "curved",
      },
    })

    -- Lazygit integration via toggleterm
    local Terminal = require("toggleterm.terminal").Terminal
    local lazygit = Terminal:new({
      cmd = "lazygit",
      dir = "git_dir",
      direction = "float",
      float_opts = {
        border = "curved",
      },
      on_open = function(term)
        vim.cmd("startinsert!")
      end,
      on_close = function(term)
        vim.cmd("startinsert!")
      end,
    })

    function _lazygit_toggle()
      lazygit:toggle()
    end

    -- Which-key: Keybinding hints
    local wk = require("which-key")
    wk.setup({
      plugins = {
        marks = true,
        registers = true,
        spelling = { enabled = false },
      },
      win = {
        border = "rounded",
      },
    })

    -- Lualine: Statusline
    require("lualine").setup({
      options = {
        theme = "${colorscheme}",
        component_separators = { left = "", right = "" },
        section_separators = { left = "", right = "" },
        globalstatus = true,
      },
      sections = {
        lualine_a = { "mode" },
        lualine_b = { "branch", "diff", "diagnostics" },
        lualine_c = { { "filename", path = 1 } },
        lualine_x = { "encoding", "fileformat", "filetype" },
        lualine_y = { "progress" },
        lualine_z = { "location" },
      },
    })

    -- Comment.nvim: Easy commenting
    require("Comment").setup({
      toggler = {
        line = "gcc",
        block = "gbc",
      },
      opleader = {
        line = "gc",
        block = "gb",
      },
    })

    -- Autopairs: Auto-close brackets
    require("nvim-autopairs").setup({
      check_ts = true,
      ts_config = {
        lua = { "string", "source" },
        javascript = { "string", "template_string" },
      },
    })

    -- ----------------------------------------------------------------------------
    -- LSP CONFIGURATION
    -- Languages: Rust, Nix, Python, TypeScript/JavaScript, Go, Lua
    -- ----------------------------------------------------------------------------

    local lspconfig = require("lspconfig")
    local capabilities = require("cmp_nvim_lsp").default_capabilities()

    -- Common on_attach for all LSP servers
    local on_attach = function(client, bufnr)
      local opts = { buffer = bufnr, silent = true }

      -- LSP keybindings (documented in which-key)
      vim.keymap.set("n", "gD", vim.lsp.buf.declaration, vim.tbl_extend("force", opts, { desc = "Go to declaration" }))
      vim.keymap.set("n", "gd", vim.lsp.buf.definition, vim.tbl_extend("force", opts, { desc = "Go to definition" }))
      vim.keymap.set("n", "K", vim.lsp.buf.hover, vim.tbl_extend("force", opts, { desc = "Hover documentation" }))
      vim.keymap.set("n", "gi", vim.lsp.buf.implementation, vim.tbl_extend("force", opts, { desc = "Go to implementation" }))
      vim.keymap.set("n", "<C-k>", vim.lsp.buf.signature_help, vim.tbl_extend("force", opts, { desc = "Signature help" }))
      vim.keymap.set("n", "<leader>rn", vim.lsp.buf.rename, vim.tbl_extend("force", opts, { desc = "Rename symbol" }))
      vim.keymap.set("n", "<leader>ca", vim.lsp.buf.code_action, vim.tbl_extend("force", opts, { desc = "Code action" }))
      vim.keymap.set("n", "gr", vim.lsp.buf.references, vim.tbl_extend("force", opts, { desc = "Find references" }))
      vim.keymap.set("n", "<leader>f", function() vim.lsp.buf.format({ async = true }) end, vim.tbl_extend("force", opts, { desc = "Format buffer" }))

      -- Diagnostics
      vim.keymap.set("n", "[d", vim.diagnostic.goto_prev, vim.tbl_extend("force", opts, { desc = "Previous diagnostic" }))
      vim.keymap.set("n", "]d", vim.diagnostic.goto_next, vim.tbl_extend("force", opts, { desc = "Next diagnostic" }))
      vim.keymap.set("n", "<leader>d", vim.diagnostic.open_float, vim.tbl_extend("force", opts, { desc = "Show diagnostic" }))
    end

    -- Rust (rust-analyzer)
    lspconfig.rust_analyzer.setup({
      capabilities = capabilities,
      on_attach = on_attach,
      settings = {
        ["rust-analyzer"] = {
          checkOnSave = { command = "clippy" },
          cargo = { allFeatures = true },
        },
      },
    })

    -- Nix (nil)
    lspconfig.nil_ls.setup({
      capabilities = capabilities,
      on_attach = on_attach,
      settings = {
        ["nil"] = {
          formatting = { command = { "nixfmt" } },
        },
      },
    })

    -- Python (pyright)
    lspconfig.pyright.setup({
      capabilities = capabilities,
      on_attach = on_attach,
    })

    -- TypeScript/JavaScript (ts_ls - successor to tsserver)
    lspconfig.ts_ls.setup({
      capabilities = capabilities,
      on_attach = on_attach,
    })

    -- Go (gopls)
    lspconfig.gopls.setup({
      capabilities = capabilities,
      on_attach = on_attach,
      settings = {
        gopls = {
          analyses = {
            unusedparams = true,
          },
          staticcheck = true,
        },
      },
    })

    -- Lua (lua-ls)
    lspconfig.lua_ls.setup({
      capabilities = capabilities,
      on_attach = on_attach,
      settings = {
        Lua = {
          runtime = { version = "LuaJIT" },
          diagnostics = { globals = { "vim" } },
          workspace = { library = vim.api.nvim_get_runtime_file("", true) },
          telemetry = { enable = false },
        },
      },
    })

    -- ----------------------------------------------------------------------------
    -- COMPLETION (nvim-cmp)
    -- ----------------------------------------------------------------------------

    local cmp = require("cmp")
    local luasnip = require("luasnip")

    cmp.setup({
      snippet = {
        expand = function(args)
          luasnip.lsp_expand(args.body)
        end,
      },
      mapping = cmp.mapping.preset.insert({
        ["<C-b>"] = cmp.mapping.scroll_docs(-4),
        ["<C-f>"] = cmp.mapping.scroll_docs(4),
        ["<C-Space>"] = cmp.mapping.complete(),
        ["<C-e>"] = cmp.mapping.abort(),
        ["<CR>"] = cmp.mapping.confirm({ select = true }),
        ["<Tab>"] = cmp.mapping(function(fallback)
          if cmp.visible() then
            cmp.select_next_item()
          elseif luasnip.expand_or_jumpable() then
            luasnip.expand_or_jump()
          else
            fallback()
          end
        end, { "i", "s" }),
        ["<S-Tab>"] = cmp.mapping(function(fallback)
          if cmp.visible() then
            cmp.select_prev_item()
          elseif luasnip.jumpable(-1) then
            luasnip.jump(-1)
          else
            fallback()
          end
        end, { "i", "s" }),
      }),
      sources = cmp.config.sources({
        { name = "nvim_lsp" },
        { name = "luasnip" },
        { name = "path" },
      }, {
        { name = "buffer" },
      }),
    })

    -- ----------------------------------------------------------------------------
    -- KEYBINDINGS
    -- Space as leader, documented with which-key
    -- ----------------------------------------------------------------------------

    -- Register key groups with which-key
    wk.add({
      { "<leader>f", group = "Find (Telescope)" },
      { "<leader>g", group = "Git" },
      { "<leader>h", group = "Hunks (Git)" },
      { "<leader>l", group = "LSP" },
    })

    local map = vim.keymap.set

    -- <leader>ff: Telescope find files
    map("n", "<leader>ff", "<cmd>Telescope find_files<cr>", { desc = "Find files" })

    -- <leader>fg: Telescope live grep
    map("n", "<leader>fg", "<cmd>Telescope live_grep<cr>", { desc = "Live grep" })

    -- <leader>fb: Telescope buffers
    map("n", "<leader>fb", "<cmd>Telescope buffers<cr>", { desc = "Find buffers" })

    -- <leader>fh: Telescope help tags
    map("n", "<leader>fh", "<cmd>Telescope help_tags<cr>", { desc = "Help tags" })

    -- <leader>fr: Telescope recent files
    map("n", "<leader>fr", "<cmd>Telescope oldfiles<cr>", { desc = "Recent files" })

    -- <leader>e: Toggle oil.nvim (file explorer)
    map("n", "<leader>e", "<cmd>Oil<cr>", { desc = "File explorer (Oil)" })

    -- <leader>gg: Lazygit
    map("n", "<leader>gg", "<cmd>lua _lazygit_toggle()<cr>", { desc = "Lazygit" })

    -- <leader>t: Toggle terminal
    map("n", "<leader>t", "<cmd>ToggleTerm<cr>", { desc = "Toggle terminal" })

    -- Better window navigation
    map("n", "<C-h>", "<C-w>h", { desc = "Move to left window" })
    map("n", "<C-j>", "<C-w>j", { desc = "Move to bottom window" })
    map("n", "<C-k>", "<C-w>k", { desc = "Move to top window" })
    map("n", "<C-l>", "<C-w>l", { desc = "Move to right window" })

    -- Resize windows with arrows
    map("n", "<C-Up>", "<cmd>resize +2<cr>", { desc = "Increase window height" })
    map("n", "<C-Down>", "<cmd>resize -2<cr>", { desc = "Decrease window height" })
    map("n", "<C-Left>", "<cmd>vertical resize -2<cr>", { desc = "Decrease window width" })
    map("n", "<C-Right>", "<cmd>vertical resize +2<cr>", { desc = "Increase window width" })

    -- Buffer navigation
    map("n", "<S-l>", "<cmd>bnext<cr>", { desc = "Next buffer" })
    map("n", "<S-h>", "<cmd>bprevious<cr>", { desc = "Previous buffer" })
    map("n", "<leader>bd", "<cmd>bdelete<cr>", { desc = "Delete buffer" })

    -- Clear search highlight
    map("n", "<Esc>", "<cmd>nohlsearch<cr>", { desc = "Clear search highlight" })

    -- Stay in visual mode when indenting
    map("v", "<", "<gv", { desc = "Indent left" })
    map("v", ">", ">gv", { desc = "Indent right" })

    -- Move lines up/down in visual mode
    map("v", "J", ":m '>+1<cr>gv=gv", { desc = "Move line down" })
    map("v", "K", ":m '<-2<cr>gv=gv", { desc = "Move line up" })

    -- Better paste (don't overwrite register)
    map("v", "p", '"_dP', { desc = "Paste without overwrite" })

    -- Terminal mode escape
    map("t", "<Esc>", "<C-\\><C-n>", { desc = "Exit terminal mode" })
    map("t", "<C-h>", "<C-\\><C-n><C-w>h", { desc = "Move to left window" })
    map("t", "<C-j>", "<C-\\><C-n><C-w>j", { desc = "Move to bottom window" })
    map("t", "<C-k>", "<C-\\><C-n><C-w>k", { desc = "Move to top window" })
    map("t", "<C-l>", "<C-\\><C-n><C-w>l", { desc = "Move to right window" })

    -- Quick save
    map("n", "<leader>w", "<cmd>w<cr>", { desc = "Save file" })
    map("n", "<leader>q", "<cmd>q<cr>", { desc = "Quit" })

    -- ----------------------------------------------------------------------------
    -- END OF CONFIGURATION
    -- ----------------------------------------------------------------------------
  '';
in {
  options.homeModules.neovim = {
    enable = lib.mkEnableOption "neovim with full IDE configuration";
  };

  config = lib.mkIf cfg.enable {
    programs.neovim = {
      enable = true;
      defaultEditor = true;
      viAlias = true;
      vimAlias = true;
      vimdiffAlias = true;

      # Lua config injected via extraLuaConfig
      extraLuaConfig = luaConfig;

      # Plugins with lazy loading where appropriate
      plugins = with pkgs.vimPlugins; [
        # Colorschemes (load the one matching system theme)
        catppuccin-nvim
        tokyonight-nvim
        {
          plugin = everforest;
          type = "lua";
          config = ""; # Configured in luaConfig
        }

        # Treesitter (syntax highlighting)
        {
          plugin = nvim-treesitter.withAllGrammars;
          type = "lua";
          config = ""; # Configured in luaConfig
        }

        # Telescope (fuzzy finder)
        telescope-nvim
        plenary-nvim # Required dependency

        # File explorer
        oil-nvim
        nvim-web-devicons # Icons for oil and other plugins

        # Git
        gitsigns-nvim

        # Terminal
        toggleterm-nvim

        # UI
        which-key-nvim
        lualine-nvim

        # Editing
        comment-nvim
        nvim-autopairs

        # LSP
        nvim-lspconfig

        # Completion
        nvim-cmp
        cmp-nvim-lsp
        cmp-buffer
        cmp-path
        luasnip
        cmp_luasnip
      ];

      # External tools for LSP servers
      extraPackages = with pkgs; [
        # LSP servers
        rust-analyzer # Rust
        nil # Nix
        nixfmt-rfc-style # Nix formatter
        pyright # Python
        nodePackages.typescript-language-server # TypeScript/JavaScript
        gopls # Go
        lua-language-server # Lua

        # Tools
        lazygit # Git TUI
        ripgrep # For Telescope live_grep
        fd # For Telescope find_files
      ];
    };

    # Enable lazygit for the terminal integration
    programs.lazygit.enable = true;
  };
}
