# Niri compositor user configuration
# Configures keybindings, window rules, and appearance via XDG config
{
  config,
  lib,
  pkgs,
  ...
}: let
  cfg = config.homeModules.niri;
  colors = config.homeModules.theme.colors;

  # Niri uses KDL config format
  niriConfig = ''
    // Niri Configuration
    // Generated by home-manager
    // Theme: ${config.homeModules.theme.name}

    // ═══════════════════════════════════════════════════════════════════════════
    // INPUT CONFIGURATION
    // ═══════════════════════════════════════════════════════════════════════════
    input {
        keyboard {
            xkb {
                layout "us"
            }
            repeat-delay 300
            repeat-rate 50
        }
        touchpad {
            tap
            natural-scroll
            scroll-method "two-finger"
        }
        mouse {
            accel-profile "flat"
        }
        focus-follows-mouse max-scroll-amount="0%"
    }

    // ═══════════════════════════════════════════════════════════════════════════
    // LAYOUT CONFIGURATION
    // ═══════════════════════════════════════════════════════════════════════════
    layout {
        gaps 8
        center-focused-column "never"
        
        default-column-width { proportion 0.5; }
        
        border {
            width 2
            active-color "${colors.primary}"
            inactive-color "${colors.surface0}"
        }
        
        focus-ring {
            off
        }
    }

    // ═══════════════════════════════════════════════════════════════════════════
    // APPEARANCE
    // ═══════════════════════════════════════════════════════════════════════════
    prefer-no-csd
    
    screenshot-path "~/Pictures/Screenshots/Screenshot from %Y-%m-%d %H-%M-%S.png"

    // ═══════════════════════════════════════════════════════════════════════════
    // ANIMATIONS (fast and snappy)
    // ═══════════════════════════════════════════════════════════════════════════
    animations {
        slowdown 0.8
        
        workspace-switch {
            duration-ms 200
            curve "ease-out-cubic"
        }
        
        window-open {
            duration-ms 150
            curve "ease-out-expo"
        }
        
        window-close {
            duration-ms 100
            curve "ease-out-quad"
        }
        
        horizontal-view-movement {
            duration-ms 150
            curve "ease-out-cubic"
        }
        
        window-movement {
            duration-ms 150
            curve "ease-out-cubic"
        }
        
        window-resize {
            duration-ms 150
            curve "ease-out-cubic"
        }
        
        config-notification-open-close {
            duration-ms 200
            curve "ease-out-cubic"
        }
    }

    // ═══════════════════════════════════════════════════════════════════════════
    // WINDOW RULES
    // ═══════════════════════════════════════════════════════════════════════════
    
    // Terminals - slightly transparent
    window-rule {
        match app-id=r#"Alacritty|kitty|foot|wezterm"#
        opacity 0.95
    }
    
    // Browsers - full opacity
    window-rule {
        match app-id=r#"firefox|chromium|brave"#
        opacity 1.0
    }
    
    // Floating dialogs
    window-rule {
        match app-id=r#"pavucontrol|nm-connection-editor|blueman"#
        open-floating true
    }
    
    // Picture-in-Picture
    window-rule {
        match title="Picture-in-Picture"
        open-floating true
    }

    // ═══════════════════════════════════════════════════════════════════════════
    // KEYBINDINGS
    // Super key is the primary modifier
    // ═══════════════════════════════════════════════════════════════════════════
    binds {
        // ─────────────────────────────────────────────────────────────────────
        // Application Launchers
        // ─────────────────────────────────────────────────────────────────────
        Mod+Return { spawn "alacritty"; }           // Terminal
        Mod+D { spawn "fuzzel"; }                   // App launcher
        Mod+E { spawn "thunar"; }                   // File manager
        Mod+B { spawn "firefox"; }                  // Browser

        // ─────────────────────────────────────────────────────────────────────
        // Window Management
        // ─────────────────────────────────────────────────────────────────────
        Mod+Q { close-window; }                     // Close window
        Mod+F { maximize-column; }                  // Maximize/fullscreen
        Mod+Shift+F { fullscreen-window; }          // True fullscreen
        Mod+V { toggle-window-floating; }           // Toggle floating

        // ─────────────────────────────────────────────────────────────────────
        // Focus Navigation (vim-style + arrows)
        // ─────────────────────────────────────────────────────────────────────
        Mod+H { focus-column-left; }
        Mod+J { focus-window-down; }
        Mod+K { focus-window-up; }
        Mod+L { focus-column-right; }
        Mod+Left { focus-column-left; }
        Mod+Down { focus-window-down; }
        Mod+Up { focus-window-up; }
        Mod+Right { focus-column-right; }

        // ─────────────────────────────────────────────────────────────────────
        // Move Windows (vim-style + arrows)
        // ─────────────────────────────────────────────────────────────────────
        Mod+Shift+H { move-column-left; }
        Mod+Shift+J { move-window-down; }
        Mod+Shift+K { move-window-up; }
        Mod+Shift+L { move-column-right; }
        Mod+Shift+Left { move-column-left; }
        Mod+Shift+Down { move-window-down; }
        Mod+Shift+Up { move-window-up; }
        Mod+Shift+Right { move-column-right; }

        // ─────────────────────────────────────────────────────────────────────
        // Workspace Navigation
        // ─────────────────────────────────────────────────────────────────────
        Mod+1 { focus-workspace 1; }
        Mod+2 { focus-workspace 2; }
        Mod+3 { focus-workspace 3; }
        Mod+4 { focus-workspace 4; }
        Mod+5 { focus-workspace 5; }
        Mod+6 { focus-workspace 6; }
        Mod+7 { focus-workspace 7; }
        Mod+8 { focus-workspace 8; }
        Mod+9 { focus-workspace 9; }

        // Move window to workspace
        Mod+Shift+1 { move-column-to-workspace 1; }
        Mod+Shift+2 { move-column-to-workspace 2; }
        Mod+Shift+3 { move-column-to-workspace 3; }
        Mod+Shift+4 { move-column-to-workspace 4; }
        Mod+Shift+5 { move-column-to-workspace 5; }
        Mod+Shift+6 { move-column-to-workspace 6; }
        Mod+Shift+7 { move-column-to-workspace 7; }
        Mod+Shift+8 { move-column-to-workspace 8; }
        Mod+Shift+9 { move-column-to-workspace 9; }

        // Workspace cycling
        Mod+Tab { focus-workspace-down; }
        Mod+Shift+Tab { focus-workspace-up; }

        // ─────────────────────────────────────────────────────────────────────
        // Monitor Navigation (Ctrl modifier)
        // ─────────────────────────────────────────────────────────────────────
        Mod+Ctrl+H { focus-monitor-left; }
        Mod+Ctrl+L { focus-monitor-right; }
        Mod+Ctrl+Left { focus-monitor-left; }
        Mod+Ctrl+Right { focus-monitor-right; }
        Mod+Ctrl+Shift+H { move-column-to-monitor-left; }
        Mod+Ctrl+Shift+L { move-column-to-monitor-right; }

        // ─────────────────────────────────────────────────────────────────────
        // Column/Window Sizing
        // ─────────────────────────────────────────────────────────────────────
        Mod+Minus { set-column-width "-10%"; }
        Mod+Equal { set-column-width "+10%"; }
        Mod+Shift+Minus { set-window-height "-10%"; }
        Mod+Shift+Equal { set-window-height "+10%"; }

        // Preset widths
        Mod+R { switch-preset-column-width; }

        // ─────────────────────────────────────────────────────────────────────
        // Screenshots (using grim + slurp)
        // ─────────────────────────────────────────────────────────────────────
        Print { screenshot; }                                    // Full screen
        Mod+Shift+S { screenshot-screen; }                       // Current screen
        Mod+Print { screenshot-window; }                         // Current window

        // ─────────────────────────────────────────────────────────────────────
        // Media Keys
        // ─────────────────────────────────────────────────────────────────────
        XF86AudioRaiseVolume { spawn "wpctl" "set-volume" "@DEFAULT_AUDIO_SINK@" "5%+"; }
        XF86AudioLowerVolume { spawn "wpctl" "set-volume" "@DEFAULT_AUDIO_SINK@" "5%-"; }
        XF86AudioMute { spawn "wpctl" "set-mute" "@DEFAULT_AUDIO_SINK@" "toggle"; }
        XF86AudioMicMute { spawn "wpctl" "set-mute" "@DEFAULT_AUDIO_SOURCE@" "toggle"; }
        XF86MonBrightnessUp { spawn "brightnessctl" "set" "5%+"; }
        XF86MonBrightnessDown { spawn "brightnessctl" "set" "5%-"; }
        XF86AudioPlay { spawn "playerctl" "play-pause"; }
        XF86AudioNext { spawn "playerctl" "next"; }
        XF86AudioPrev { spawn "playerctl" "previous"; }

        // ─────────────────────────────────────────────────────────────────────
        // Session Management
        // ─────────────────────────────────────────────────────────────────────
        Mod+Escape { spawn "swaylock"; }             // Lock screen
        Mod+Shift+E { quit; }                        // Exit niri

        // ─────────────────────────────────────────────────────────────────────
        // Layout Toggles
        // ─────────────────────────────────────────────────────────────────────
        Mod+W { toggle-column-tabbed; }              // Toggle tabbed column
        Mod+Comma { consume-window-into-column; }    // Add window to column
        Mod+Period { expel-window-from-column; }     // Remove from column
    }

    // ═══════════════════════════════════════════════════════════════════════════
    // STARTUP APPLICATIONS
    // ═══════════════════════════════════════════════════════════════════════════
    spawn-at-startup "waybar"
    spawn-at-startup "mako"
  '';
in {
  options.homeModules.niri = {
    enable = lib.mkEnableOption "niri user configuration";
  };

  config = lib.mkIf cfg.enable {
    # Write niri config via XDG
    xdg.configFile."niri/config.kdl".text = niriConfig;
  };
}
